In [33]:
import numpy as np
a = np.ones((6,4))
a[range(4),range(4)]=2
a

array([[2., 1., 1., 1.],
       [1., 2., 1., 1.],
       [1., 1., 2., 1.],
       [1., 1., 1., 2.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
inxs = np.where(a==2)
a[inxs]

array([2., 2., 2., 2.])

In [3]:
np.where(a==2)[0]

array([0, 1, 2, 3])

In [6]:
inxs = np.where(a==2)
for ix in range(len(inxs[0])):
    i = inxs[0][ix]
    j = inxs[1][ix]
    print(i,j)

0 0
1 1
2 2
3 3


In [11]:
for i in zip(*inxs):
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)


In [12]:
*inxs

SyntaxError: can't use starred expression here (<ipython-input-12-300b81e99ca6>, line 4)

In [14]:
a=np.ones((4,))
a

array([1., 1., 1., 1.])

In [15]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [16]:
a.shape

(4,)

In [19]:
np.array(np.ones((4,1)).flat)

array([1., 1., 1., 1.])

In [27]:
np.ones((4,)).reshape(-1,1)

array([[1.],
       [1.],
       [1.],
       [1.]])

In [29]:
b=[[2,3,4],[5,6,7]]
b

[[2, 3, 4], [5, 6, 7]]

In [30]:
b[1][1]

6

In [32]:
b_np = np.array(b)
b_np[1,1]

6

In [ ]:
b_np = 